name: Sprawdzanie HTML

on: [push, pull_request]

jobs:
  htmlhint:
    runs-on: ubuntu-latest
        steps:
      - name: Pobierz kod z repozytorium
        uses: actions/checkout@v4

      - name: Uruchom walidator HTMLHint
        uses: htmlhint/htmlhint-action@v2
        with:
          html_path: 'index.html'
