name: Sprawdzanie i Automatyzacja

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod z repozytorium
        uses: actions/checkout@v4

      - name: Konfiguracja srodowiska Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Zainstaluj Biome w locie
        run: npm install -g @biomejs/biome

      - name: Generuj mape strony i robots
        run: node generate-sitemap.js
        
      - name: Uruchom sprawdzanie i naprawianie kodu (Biome)
        run: biome check --write . || true

      - name: Generuj mape strony i robots
        run: node generate-sitemap.js

