
name: Automatyczna naprawa formatowania
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Uruchom Prettier i napraw błędy
        uses: crey08/prettier-action@v4.3
        with:
          # Ta opcja sprawi, że Prettier sam poprawi pliki
          prettier_options: --write **/*.html
          # Automatycznie zapisz poprawiony kod w repozytorium
          commit_message: "Automatyczne poprawienie błędów przez Prettier"
