name: Wymuszona Codzienna Naprawa Plików
on:
  schedule:
    # 18:00 czasu polskiego (w czasie letnim to 16:00 UTC)
    - cron: '0 16 * * *'
  workflow_dispatch: # Pozwala na ręczne uruchomienie w dowolnym momencie

jobs:
  force-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pobranie kodu z repozytorium
        uses: actions/checkout@v4

      
      - name: Konfiguracja Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.0

      - name: Wymuszona próba naprawy kodu
        run: |
          biome check --write . || true

      - name: Wymuszona próba naprawy kodu
        run: |
            biome check --write . || true


      - name: Natychmiastowy zapis zmian (Wymuszony Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add .
          git commit -m "bot: wymuszona automatyczna naprawa kodu" || echo "Brak zmian do zapisania"
          git push
